### ISSUE TITLE
Non-overlapping segments reported as overlapping, doesn't account for extended address?

### ISSUE THREAD

**Issue by JeremyBCD** [marcinbor85/gohex#3]
I've found that records that have the same address in different segments are reported as overlapping when parsing a hex file.

A simple example:
 
```
:020000025000AC
:10000000A5A9AEFC5FAAB488B8A8860F8BC79C943C
:0200000260009C
:10000000F384980CA450DC26572ECE667CAF34DFE8
:00000001FF
```

`ParseIntelHex()` fails to parse this, reporting an overlap on line 4. But these two records are in different segments, with non-overlapping addresses of 0x25000000 and 0x26000000.

(Thanks for making such a handy library, it's working great for my single-segment files! Not sure how to fix this issue.)

**Comment by marcinbor85** [comment]
Hi.
Thanks for issue report.
At Your example, there are records type (0x02) with 20-bit extended address, which is not supported.
These records were simple ignored without any error so both data records were overlapped.
Take a look at the newest implementation.
Solution is implemented here: https://github.com/marcinbor85/gohex/pull/4

Also, there was other PR with this functionality already implemented.
I have merged it, so on master branch should works well also for Your case.
Regards
MB

**Comment by marcinbor85** [comment]
solved

**Comment by JeremyBCD** [comment]
@marcinbor85 Tested this, the issue is fixed!
